### PR TITLE
Fix walks when the prefix doesn't match any strings

### PR DESCRIPTION
**Pull request by sunshowers**
Currently, the walk code doesn't check to see if any prefixes matching the
string actually exist.

### CODE REVIEW

**Comment by sunshowers** [comment]
ping, @jgehring?

**Comment by jgehring** [comment]
Sorry for the delay, I'll look into this soon.

**Comment by jgehring** [comment]
Finally got around to verify and merge this; thanks a lot for the fix!

In order to speed up future fixes, I've added you as a collaborator. Please feel free to just commit next time, or add a pull request for discussion if necessary. Thanks again!

**Comment by sunshowers** [comment]
Heh, thanks, but I've set aside using critbit trees for my work project now. For the project I was using it for, critbit trees (which I was using as tree-based maps) turned out to be a win over hash tables, but not enough of a win to justify that much extra C code. :)

Regardless, I'll try looking at the code and seeing if there are any other fixes I could upstream.

**Pull request merged**
